### ISSUE TITLE
Slab revolver flash don't get removed

### ISSUE THREAD

**Issue by Glebux** [Hydraxous/UltraFunGuns#12]
![ULTRAKILL_TxnZC94hkv](https://user-images.githubusercontent.com/58988874/192620996-228c0326-5f40-4382-9565-c1a2dc94a4bd.png)
Error log:

[22:43:57.2] [Error] NullReferenceException: Object reference not set to an instance of an object
UltraFunGuns.BeamPatch.Prefix (RevolverBeam __instance, UnityEngine.RaycastHit currentHit) (at <9771bee6ddc84b43845a0b9fcbebbb35>:0)
RevolverBeam.ExecuteHits (UnityEngine.RaycastHit currentHit) (at <ba0ba0851e804e1ab6533ea5a3d4d7bb>:0)
RevolverBeam.PiercingShotCheck () (at <ba0ba0851e804e1ab6533ea5a3d4d7bb>:0)

**Comment by Hydraxous** [comment]
Thanks for submitting this issue, I will look into it.
