### ISSUE TITLE
Does not work if put in ultra mod managers mod folder

### ISSUE THREAD

**Issue by sm64onlydude** [Hydraxous/UltraFunGuns#18]
The weapons will not work if you move the mods dll to ultramodmanagers mod folder, and only works while its in bepinex/plugins

**Comment by Hydraxous** [comment]
UFG is a BepInEx plugin, not a UMM mod, so it supposed to reside within BepInEx/plugins. It should load alongside UMM without issues. If there are issues with specific UMM mods or mods in general you can submit new issues posts for them.

**Comment by sm64onlydude** [comment]
to my knowledge bepinex mods should work with umm, not to sure with that
thou

**Comment by sm64onlydude** [comment]
ahh ok, will there be any plans for it to be fixed on umm?

**Comment by Hydraxous** [comment]
I wanted to come back and apologize. I was entirely wrong. UMM does support loading Bepinex mods so the issue was a real issue and not user error. I am sorry for my ignorance.
