### ISSUE TITLE
Weapons not being deployed when other mods are present

### ISSUE THREAD

**Issue by Hydraxous** [Hydraxous/UltraFunGuns#3]

**Comment by YourLocalMedic** [comment]
I'm also having this issue even without other mods installed, however I'm playing on Linux. The only way i can get them to deploy is by unequipping all vanilla weaponry, pressing the appropriate key, walking up to the terminal and stepping away from it.

**Comment by Hydraxous** [comment]
Unfortunately, I don't have a Linux system to test this on atm. I have overhauled the weapon deployment system for the upcoming release so if the problem persists then I can investigate it.
