### ISSUE TITLE
normal weapons are invisible

### ISSUE THREAD

**Issue by lololtobieninjaaltolol** [Hydraxous/UltraFunGuns#36]
after i use the ufg guns and switch to normal again they are just invisible

**Comment by Hydraxous** [comment]
Are you on the current release, 1.1.7?

**Comment by Hydraxous** [comment]
1.2.0 changes and reworks many things, if the issue still exists in the new version, please open a new issue.

**Comment by FishEater539** [comment]
same issue here, im using the ultrakill build 14102728
