### ISSUE TITLE
Weapons do not have shaders compiled for OpenGLCore

### ISSUE THREAD

**Issue by coatlessali** [Hydraxous/UltraFunGuns#41]
Below instructions should fix, and allow shaders to load on MacOS/Linux (Native). Test by adding `-force-glcore` to your launch options on Steam.
![20230517_13h06m16s_grim](https://github.com/Hydraxous/UltraFunGuns/assets/61166135/2693bd91-bc62-4ef7-b8e6-fcd993d02711)

**Comment by MechaXYZ** [comment]
could you somehow do this yourself and make a pr? i need the full ultraballin'™ experience

**Comment by coatlessali** [comment]
> could you somehow do this yourself and make a pr? i need the full ultraballin'™ experience

I don't have the unity project, so I cannot.

**Comment by Hydraxous** [comment]
This issue should be fixed in latest 1.2.2
Please re-open if issue persists.
