### ISSUE TITLE
UltraFunGuns doesnt apply in sandbox mode

### ISSUE THREAD

**Issue by TheHalfBunny** [Hydraxous/UltraFunGuns#44]
title says it all
here's a video
https://streamable.com/g8k8uc link cuz video too big ;C

**Comment by Hydraxous** [comment]
It seems you have more than just UFG installed, its possible another mod is causing the issue.
Would you mind going into the game files and grabbing the log.txt file from the folder containing UltraFunGuns.dll, then attaching it to your reply. It would greatly help me understand the issue.

Thanks

**Comment by TheHalfBunny** [comment]
[log.txt](https://github.com/Hydraxous/UltraFunGuns/files/11780310/log.txt)

**Comment by TheHalfBunny** [comment]
> It seems you have more than just UFG installed, its possible another mod is causing the issue. Would you mind going into the game files and grabbing the log.txt file from the folder containing UltraFunGuns.dll, then attaching it to your reply. It would greatly help me understand the issue.
> 
> Thanks
[log.txt](https://github.com/Hydraxous/UltraFunGuns/files/11781986/log.txt)

**Comment by Hydraxous** [comment]
Looks like you are using UltraShit modpack. Not recommended, It has broken mods which also cause UFG to break.
Its possible that there are also duplicate dlls in your plugins folder also due to UltraShit which can cause various issues, try checking if that is the case as it may resolve the issue.

**Comment by TheHalfBunny** [comment]
> Looks like you are using UltraShit modpack. Not recommended, It has broken mods which also cause UFG to break. Its possible that there are also duplicate dlls in your plugins folder also due to UltraShit which can cause various issues, try checking if that is the case as it may resolve the issue.

thanks for that, might aswell update it :)

**Comment by TheHalfBunny** [comment]
i found something out

**Comment by TheHalfBunny** [comment]
the ultrakull mod is making the problem

**Comment by TheHalfBunny** [comment]
![image](https://github.com/Hydraxous/UltraFunGuns/assets/84818665/6ec9728c-b92d-40a7-9be6-db8ae2ccedcd)
