### ISSUE TITLE
Weapon manager, keybinds, and a good portion of the weapons non functional

### ISSUE THREAD

**Issue by OvercomeXD** [Hydraxous/UltraFunGuns#48]
I haven't a clue how making ultrakill mods works, and appearently i dont know how to install them properly either, i dont know it just aint working

here be the log
[log.txt](https://github.com/Hydraxous/UltraFunGuns/files/12851149/log.txt)

Edit: I did some digging and unburied a different problem, the config file where i am supposed to change the keybinds just isn't there

here is a screenshot showing the config folder

![explorer_sVCCHgSDoL](https://github.com/Hydraxous/UltraFunGuns/assets/147441334/54feaff0-b364-427e-b86d-564de92b14ec)

**Comment by nosh62** [comment]
This shouldn't be that hard.
All you should have to do is:
1. Download both HydraDynamics and UFG;
2. Put the HydraDynamics folder into .../ULTRAKILL/BepInEx/plugins;
3. Put the UFG folder into .../ULTRAKILL/BepInEx/plugins;
And just open the game.

**Comment by programming-hampter** [comment]
Everything is correct here, the update is fucked though. Just wait a bit until the devs patch it.

**Comment by Hydraxous** [comment]
Fixed in 1.3.0
