### ISSUE TITLE
Mod doesn't work (at all)

### ISSUE THREAD

**Issue by programming-hampter** [Hydraxous/UltraFunGuns#59]
Bug:
Mod does not work.

Reproduce:
1. Have ultrakill Violent Night update. (not anything later than C version)
2. Do anything.

Logs:
[preloader_20240126_150957_578.log](https://github.com/Hydraxous/UltraFunGuns/files/14076486/preloader_20240126_150957_578.log)
[LogOutput.log](https://github.com/Hydraxous/UltraFunGuns/files/14076487/LogOutput.log)
[log.txt](https://github.com/Hydraxous/UltraFunGuns/files/14076488/log.txt)

Edit:
You may see in logs that I was using Voxel Update, not the hotfix version. I tried both: both failed.

**Comment by Hydraxous** [comment]
There is no release that currently supports violent night update. Latest 1.3.1 only supports 14c and 14d

**Comment by programming-hampter** [comment]
well i am using 14b, doesn't work

**Comment by LoganTheAroAce** [comment]
just update your game. Most mods that support 14b have likely updated to 14c and or 14d
