### ISSUE TITLE
i cant equip the weapons

### ISSUE THREAD

**Issue by nerkmon** [Hydraxous/UltraFunGuns#61]
whenever i try to use the weapons in the inventory or equip them through the keybinds it either doesent do anything or show the weapon in the hud but not have anything in my hand or function at all

1. Go to the inventory (or use one of the keybinds to equip the weapons)
2. Click on one of the weapons
3. go out of the menu
4. no weapon :(

i wanted to get a funny weapon and be able to use it funnily

i asked on the ultrakill modding discord but there aint nothin

pls help i just want to hit people with a funny brick

**Comment by Hydraxous** [comment]
fixed in [Release-1.3.4](https://github.com/Hydraxous/UltraFunGuns/releases/tag/Release-1.3.4)
