### ISSUE TITLE
I Cannot Download 1.3.4

### ISSUE THREAD

**Issue by FishRP7** [Hydraxous/UltraFunGuns#62]
Hi,
When I Go To Download The Mod And Install It, The File Say's 1.3.4, However Once I Entire The UFG Menu It Says I Have Version 1.3.3 And Should Update Because I Am Outdated I Believe The Mod Isn't Functioning Correctly I Cannot Switch Weapons With The Number Keys and Many Of The Weapons Don't Shoot Or Don't Work Correctly. 
Any Help Would Be Appreciated, Thanks.

**Comment by Hydraxous** [comment]
Epic fail on my end, I forgot to update the version in the mod.

**Comment by FishRP7** [comment]
Ok Thanks The Red Error Messages Are Attached, 
![First Error](https://github.com/Hydraxous/UltraFunGuns/assets/170606430/683137e0-bfef-4f69-9a85-0b2a8b9ecbd1)
![fifth error](https://github.com/Hydraxous/UltraFunGuns/assets/170606430/67a1a013-4c03-4b17-bfa6-43b338b47c4b)
![fourth error](https://github.com/Hydraxous/UltraFunGuns/assets/170606430/c5c7030b-8714-40f3-950e-dd4a1bba2805)
![second error](https://github.com/Hydraxous/UltraFunGuns/assets/170606430/e512eede-594a-4f3f-8443-0f212b5df900)
![seventh error](https://github.com/Hydraxous/UltraFunGuns/assets/170606430/d38e4e0e-d98e-4f56-a0f0-583fd04fd4e4)
![sixth error](https://github.com/Hydraxous/UltraFunGuns/assets/170606430/d8df5f23-3164-422c-a7b4-9d9f2c584967)
![Third Error](https://github.com/Hydraxous/UltraFunGuns/assets/170606430/36862b7f-09c9-432f-b3bc-aa7de93b9e96)


Please Find Attached Hopefully The images im very new to github and places like this for the image labeled seventh layer that is so you can see how far the errors extend down im afriad i dont have the time to ss every single one. 
Thanks

**Comment by Hydraxous** [comment]
Thanks for those images. The errors provided suggest that the ULTRAKILL version you're using is outdated.

To get UFG working you will have to do one of the following
- Update ULTRAKILL
- Try older versions of UFG such as 1.3.3 (ironically)

I must be clear however, I don't have any plans to release builds of UFG for outdated ULTRAKILL versions. So if previous UFG versions are not compatible with your game version, you will have to update your game if you'd like to use the mod.
